config/routes.rb
Rails.application.routes.draw do
  scope '/checkout' do 
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  post 'items/add_to_cart/:id', to: 'items#add_to_cart', as: 'add_to_cart'
  delete 'items/remove_from_cart/:id', to: 'items#remove_from_cart', as: 'remove_from_cart'

  resources :items
  root to: 'items#index'
 
  resources :landing, only: [:index, :show]
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

  def create
     item = Item.find(params[:id])

     if item.nil?
      redirect root_path
      return
     end

     # setting up a stripe session for payment.
     @session = Stripe::Checkout::Session.create(
       payment_method_types: ['card'], 
       line_items: [{
         name: item.title,
         description: item.description,
         amount: item.price_cents,
         currency: 'cad',
         quantity: 1
       }],
       success_url: checkout_success_url,
       cancel_url: checkout_cancel_url
     )

    respond_to do |format|
      format.js
    end

  end

  def success
  end

  def cancel
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :initialize_session
  before_action :increment_visit_count, only: %i[index about]
  before_action :load_cart

  # GET /items or /items.json
  def index
    @items = Item.all
    
  end

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to root_path
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to root_path
  end
  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :image)
    end

    def initialize_session
      session[:visit_count] ||= 0
      session[:cart] ||= []
    end

    def load_cart
      @cart = Item.find(session[:cart])
    end

    def increment_visit_count
      session[:visit_count] += 1
    @visit_count = session[:visit_count]
    end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/checkout/create.js.erb
const stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key]%>');

stripe.redirectToCheckout({
  sessionId: '<%= @session.id %>'
}).then (function (result){
  console.log(result.error.message);
});

app/views/checkout/success.html.erb
<h1> Success ! WE TOOK YOUR MONEY</h1>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<STYLE>

.formulaire_items{
  display: flex;
  flex-direction: column;
  justify-content: center;
  
}

.a1 {
  display: flex;
  justify-content: center;
  flex-direction: column;
}

</STYLE>


<p> Merci de renseigner les informations nécessaires à la vente de votre chat </p>

<div class="container imgcgatons">
    <img class="card-img-top" src="https://data.puzzle.be/dino.151/chatons-puzzle-150-pieces.62908-1.fs.jpg" alt="Card image cap">
</div>

<div class="container formulaire_items">
    <div class="field a1">
      <%= form.label :prénom %>
      <%= form.text_field :title %>
    </div>
  
    <br></br>
  
    <div class="field a1">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
  
    <br></br>
  
    <div class="field a1">
      <%= form.label :prix %>
      <%= form.number_field :price_cents %>
     
    </div>
  
    <br></br>
  
  

    <div class="field a1">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
  
    <br></br>
  
    <div class="actions a1">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<br></br>

<div class="row row-cols-8 row-cols-sm-8 row-cols-md-9   fig ">


  <div class="col but1">
    <h1><%= button_to "show previous post", @item, :method => "get" %></h1>         
  </div>

  <div class="col but2">
    <h1><%= button_to "Back aux items ", items_path, :method => "get" %></h1>
  </div>
</div>

<br>

<STYLE>

    .fig{
        display:flex;
        align-items: top;
        padding-right: 30px;
    }

    .but1 {
        display:flex;
        padding-left: 80px;
        padding-right: 300px;
    }

    .but2 {
        display:flex;
        
        padding-left: 10px;
    }

</STYLE>

app/views/items/index.html.erb
<style>
.create_button {
  font-weight: 1000;
  font-size:20px;
  font-family: "Lucida Console", "Courier New", monospace;
  background-color: white;
  border: none;
  color: black;
  padding: 30px 200px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  border-radius: 12px;
  border: 3px solid rgb(124, 124, 124);
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
}
.create_button:hover {
  background-color: rgb(124, 124, 124);
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
  border: 3px solid black;
} 
.cart {
  font-size: 20px;
}
</style>

<div class="cart">
<% if user_signed_in? %>
<details>
  <summary><strong>Panier :</strong></summary>
  <% if @cart.empty? %>
  <br />
  <p>Aucun article dans le panier.</p>
  <% else %>
  <ul>
    <% @cart.each do |item| %>
    <li><%= item.title %>prix :<%= number_to_currency item.price_cents / 100.0 %> - <%= link_to 'supprimer du panier', remove_from_cart_path(item), method: :delete %> </li>
  <% end %>
  </ul>
  <% end %>
</details>
<p id="notice"><%= notice %></p>
<center><%= button_to "Créer son annonce", new_item_path, :method => "get", class: "create_button" %></center>
<% else %>
</div>
<center><p> Veuillez vous identifier pour créer une annonce, ou acheter un animal.</p></center>
<% end %>

<br />
<br />

      <center>
      <h1><strong><u>Chats disponibles</u></strong></h1>  
      <p><i> certifiés pucés et vaccinés </i><p>  
      </center    
    
<div class="tout1">
  <div class="row row-cols-4 row-cols-sm-5 row-cols-md-8 ">


    

   
  </div>



  <br>


  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 ">
    <% @items.each do |item| %>
      <div class="col">
        <div class="card border-warning mb-3 cards" style="max-width: 20rem;">

          <div class="card-header">
            <center><h4>prénom : <%= item.title %></h4></center>
          </div>

          <div class="card-body">
            
            
          <div class="flex-container text">
          <center><%= image_tag(item.image,  :size => "250x200")if item.image.attached? %> </center>
            <center><h4 class="card-title">prix : <%= number_to_currency item.price_cents / 100.0 %></h4></center>
            <h6><strong>description :</strong></h6>
            <p class="card-text"><%= item.description %></p>

            <% if user_signed_in? %>

            <center><%= link_to 'Supprimer', item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-secondary'%>
            <%= link_to "Modifier", edit_item_path(item.id), class: 'btn btn-sm btn-outline-secondary'%></center>
            
          
            
              <% if @cart.include?(item) %>
              
              
              <center><p><%= button_to 'Retirer du panier', remove_from_cart_path(item, :style => "red"), method: :delete %></p> 
              </center><% else %>
              <center><p><%=  button_to 'Ajouter au panier', add_to_cart_path(item.id), method: :post %></p>
              </center><% end %>
              
              <center><%= button_to 'Acheter maintenant', checkout_create_path, method: :post, params: {id: item.id}, remote: true %>
              </center>
              
             
              <% end %></div>
            </div>
        </div>
      </div>
      
    <% end %>
  </div>
</div>






<STYLE>

.button_to1 {
  weight: 220%;
  height: 150%;
}

.tout1 {
  display:flex;
  padding-left: 30px;
  flex-direction: column;
}




</STYLE>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>


<br></br>

<a href="/">
    <button type="button" class="container  backbutton">Block level button</button>
</a> 

<br></br>

app/views/items/show.html.erb
#/items/*item ID*


<STYLE>

  .imghappycat {
    width: 40%
  }

  .itempostverifedit {
    display:flex;
    flex-grow: 10;
    display: flex;
    flex-wrap: nowrap;
    
  }
  
  @media (max-width: 800px) {
    .itempostverifedit {
      display: flex;
      flex-direction: column;
      align-items: center;
    }
  }


  @media (max-width: 800px) {
    .myrow1 {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
  }

  .myrow1{
    border: 1px solid black;
    display: flex;
    flex-wrap: nowrap;
  }

</STYLE>




<div class="row itempostverifedit">
  <div class="flex-container imghappycat">

    <img class="card-img-top" src="https://images-na.ssl-images-amazon.com/images/I/71t+aicsR0L.jpg" alt="Card image cap">

  </div>

  
  <div class="flex-container itempost">
  
    <ul class="nav nav-tabs">
      <li class="nav-item">
      
        <a class="nav-link active" data-bs-toggle="tab" href="#home">infos cool</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="tab" href="#profile">Image</a>
      </li>
      <li class="nav-item">
        <%= button_to "Modifier le post", edit_item_path(@item), :method => "get" %>
      </li>
      <li class="nav-item">
        <%= button_to "Retour au menu", href="/", :method => "get" %>
      </li>
    </ul>

    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade show active" id="home">


        <br>
          <h4>titre:<%= @item.title %></h4>

          <br>
          <p>desc :<%= @item.description %></p>

          <br></br>

          <h5>Prix :<%= number_to_currency @item.price_cents %></h5>





          </p>
        </div>
        <div class="tab-pane fade" id="profile">
        <%= image_tag(@item.image,  :size => "250x200") %>

        <br></br>


      </div>
        
    </div>
  </div>
</div>

app/views/landing/index.html.erb
#????

<div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      
      <% @items.each do |item| %>
        <div class="col">
          <div class="card shadow-sm">
          <img class="card-img-top" <%= item.image %></div>
          
            <svg class="bd-placeholder-img card-img-top"  width="auto" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title></svg>

            <div class="card-body">
              <p class="card-text"><%= item.title %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                <%= link_to "View", landing_path(item.id), class: 'btn btn-sm btn-outline-secondary'%>
              
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>

        <% end %>
        
      </div>
    </div>




    

app/views/landing/show.html.erb
<div class="container container-show">

    <div class="d-flex flex-row justify-content-center">
<div class="card show-card" style="width: 100%;">
  <img class="card-img-top" src="inserimage" alt="Card image cap">
  <div class="card-body">
    <h2 class="card-title">titre : <%= @item.title %></h2>
    <p class="card-text">description : <%= @item.description %></p>
    <h3 class="card-text">prix : <%= @item.price_cents %> €</h3>
    <a href="#" class="btn btn-primary">Ajouter au ppanier</a>
  </div>
</div>
</div>

</div>


<STYLE>
.myrow1 {
  display: flex;
  justify-content: center;
}


.imgenhaut {
    margin: 20px;
    display: flex;
    flex-wrap: wrap;
    background-position-y: center;
    background-repeat: no-repeat;

}

@media (max-width: 800px) {
    .myrow1 {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
}

.myrow1{
    
    display: flex;
    flex-wrap: nowrap;
}

.show2 {
    margin: 20px;
    display: flex;
    flex-direction: column;
   
}



.word {
   
    width: 80%;
    font-size: 100%;
    
  }



</STYLE>







  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PixelCat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all' %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <%= javascript_include_tag 'application' %>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/sketchy/bootstrap.min.css" rel="stylesheet" type="text/css">
  <link rel="stylesheet" type="text/css" href="style.css" />
  <!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Google Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">

    

<STYLE>A {text-decoration: none;} </STYLE>

<!-- Stripe -->
<script src="https://js.stripe.com/v3/"></script>

<!-- Bootstrap core CSS -->
<link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">
<title>EventBrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
    .fas  {

  font-size: 50px;
  color: black; 
  margin-right: 25px;
  }

  .signin {
    margin-right: 25px;
    display: flex;
    align-items: center;
}

  .navbar_buttons {
    font-weight:900;
    font-size:15px;
    font-family: "Lucida Console", "Courier New", monospace;
    background-color: white;
    border: none;
    color: black;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    border-radius: 12px;
    border: 2px solid rgb(124, 124, 124);
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
  }
  .navbar_buttons:hover {
    background-color: rgb(124, 124, 124);
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
    border: 3px solid black;
  } 

  }
  
    </style>

  </head>

  <body>
 
  <!-- NAVBAR -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <h1 class="my-2"><a href="/" class="btn"><i class="fas fa-cat"></i></a><%= link_to "TKP - The Kitten Place", root_path %></h1>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      </ul>
      <div class="form-inline my-2 my-lg-0">

      <h3>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <% if user_signed_in? %>
            <div class="row signin">
              <div class="col-6 ">
                <li class="nav-item active">
                </li>
              </div>  

              <br></br>

              <div class="col-6 ">
                <li class="nav-item active">
                <%= button_to "Déconnexion", destroy_user_session_path, method: :delete, class: "navbar_buttons", style: "margin-right: 100px;"%>   
                </li>
              </div>
            </div>

                   

          <% else %> 

            <div class="row signin">
              <div class="col-6 ">
                <li class="nav-item active">
                <%= button_to "Inscription", new_user_registration_path, :method => "get", class: "navbar_buttons" %> 
                </li>
              </div>  

                <br></br>

              <div class="col-6 ">
                <li class="nav-item active">
                <%= button_to "Connexion", new_user_session_path, :method => "get", class: "navbar_buttons" %>   
                </li>
              </div>

            </div>

          <% end %>
        </ul>
      </h3>
      
    </div>
  </div>
</nav>



  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>